### ISSUE TITLE
Trying to get stats when database size is too big ends in a Serialization error

### ISSUE THREAD

**Issue by chboing** [meilisearch/meilisearch-java#298]
Hello,
I tried to get the stats of my meilisearch DB and it ended with a serialization error because database size is more than MAX_INT.
`com.meilisearch.sdk.api.instance.Stats.java `object has `private int databaseSize`
And if DB is larger than 2^31-1 = 2147483647 then it fails to serialize.
My DB is more than 7GB (7701901318) , so it fails.

```
Caused by: com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 7701901318 at line 1 column 27 path $.databaseSize
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.meilisearch.sdk.json.GsonJsonHandler.decode(GsonJsonHandler.java:42)
```

**Comment by alallema** [comment]
Hi @chboing,
Thank you for raising this issue! This is indeed a problem.
PR are welcome 🔥

**Comment by diegonavarroq** [comment]
Hi, I'd like to work on this issue if no one else is working on it yet.

**Comment by alallema** [comment]
Hi @diegonavarroq,
Sure! Thanks for your interest to MeiliSearch 😊

**Comment by chboing** [comment]
Hey @diegonavarroq great news !
I'm wondering if just changing int to long would solve the pb maybe ?

**Comment by alallema** [comment]
Hi @diegonavarroq,
Yes, I think so. It allows a database size of about 9*10^9 GB if I'm not wrong. I think it is enough.

**Comment by diegonavarroq** [comment]
Yes, I thought about implementing that solution, I would only need to replicate the problem.
