### ISSUE TITLE
JacksonJsonHandler cannot parse task status enqueued 

### ISSUE THREAD

**Issue by Skillkiller** [meilisearch/meilisearch-java#604]
**Description**
I would like to create a new index. The client uses a ``new JacksonJsonHandler()``. However, when reading the task state I get an error.

**Expected behavior**
Parsing string value ``enqueued`` as enum value ``ENQUEUED``.

**Current behavior**
Currently i get the following error:
```
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:754) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:318) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[spring-boot-3.1.0.jar:3.1.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[spring-boot-3.1.0.jar:3.1.0]
	at de.skillkiller.clipindex.ClipIndexApplication.main(ClipIndexApplication.java:20) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-3.1.0.jar:3.1.0]
Caused by: java.lang.RuntimeException: Meilisearch Exception: {com.fasterxml.jackson.databind.exc.InvalidFormatException. Error=com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.meilisearch.sdk.model.TaskStatus` from String "enqueued": not one of the values accepted for Enum class: [SUCCEEDED, PROCESSING, ENQUEUED, FAILED, CANCELED]
 at [Source: (String)"{"taskUid":1,"indexUid":"clips2","status":"enqueued","type":"indexCreation","enqueuedAt":"2023-05-20T00:20:14.811110336Z"}"; line: 1, column: 43] (through reference chain: com.meilisearch.sdk.model.TaskInfo["status"])}
	at com.meilisearch.sdk.http.response.BasicResponse.create(BasicResponse.java:22) ~[meilisearch-java-0.11.1.jar:na]
	at com.meilisearch.sdk.HttpClient.post(HttpClient.java:96) ~[meilisearch-java-0.11.1.jar:na]
	at com.meilisearch.sdk.IndexesHandler.createIndex(IndexesHandler.java:52) ~[meilisearch-java-0.11.1.jar:na]
	at com.meilisearch.sdk.Client.createIndex(Client.java:73) ~[meilisearch-java-0.11.1.jar:na]
	at de.skillkiller.clipindex.MeilisearchClient.lambda$checkIndexes$0(MeilisearchClient.java:48) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:770) ~[spring-boot-3.1.0.jar:3.1.0]
	... 10 common frames omitted
Caused by: com.meilisearch.sdk.exceptions.JsonDecodingException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.meilisearch.sdk.model.TaskStatus` from String "enqueued": not one of the values accepted for Enum class: [SUCCEEDED, PROCESSING, ENQUEUED, FAILED, CANCELED]
 at [Source: (String)"{"taskUid":1,"indexUid":"clips2","status":"enqueued","type":"indexCreation","enqueuedAt":"2023-05-20T00:20:14.811110336Z"}"; line: 1, column: 43] (through reference chain: com.meilisearch.sdk.model.TaskInfo["status"])
	at com.meilisearch.sdk.json.JacksonJsonHandler.decode(JacksonJsonHandler.java:72) ~[meilisearch-java-0.11.1.jar:na]
	at com.meilisearch.sdk.http.response.BasicResponse.create(BasicResponse.java:15) ~[meilisearch-java-0.11.1.jar:na]
	... 15 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `com.meilisearch.sdk.model.TaskStatus` from String "enqueued": not one of the values accepted for Enum class: [SUCCEEDED, PROCESSING, ENQUEUED, FAILED, CANCELED]
 at [Source: (String)"{"taskUid":1,"indexUid":"clips2","status":"enqueued","type":"indexCreation","enqueuedAt":"2023-05-20T00:20:14.811110336Z"}"; line: 1, column: 43] (through reference chain: com.meilisearch.sdk.model.TaskInfo["status"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:2002) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1230) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._deserializeAltString(EnumDeserializer.java:415) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer._fromString(EnumDeserializer.java:279) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.std.EnumDeserializer.deserialize(EnumDeserializer.java:248) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:138) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3772) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.0.jar:2.15.0]
	at com.meilisearch.sdk.json.JacksonJsonHandler.decode(JacksonJsonHandler.java:65) ~[meilisearch-java-0.11.1.jar:na]
	... 16 common frames omitted

```

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
- OS: Windows 11
- Java: 17
- Meilisearch version: v.1.1.1
- meilisearch-java version: 0.11.1
- Spring Boot: 3.1.0

**Comment by brunoocasali** [comment]
Hi @Skillkiller, thanks for your report! The maintainer of this repo (@alallema) is on holiday, and we get back to you as soon as possible!

If you want to get your hands dirty, PRs are welcome! 🤘
