### ISSUE TITLE
Unable to use multisearch if jackson json handler is used

### ISSUE THREAD

**Issue by jdvalenzuelah** [meilisearch/meilisearch-java#766]
**Description**
When using JacksonJsonHandler with a default `ObjectMapper`, multisearch throws `InvalidDefinitionException` when serializing request. 
As a work around updating property visibility fixes it. 
```
objectMapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)
``` 

**Expected behavior**
It should not be needed to change property visibility to make multisearch request

**Current behavior**
Exception is thrown

**Screenshots or Logs**
```
java.lang.RuntimeException: Meilisearch Exception: {com.fasterxml.jackson.databind.exc.InvalidDefinitionException. Error=com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.meilisearch.sdk.MultiSearchRequest and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)}
	at com.meilisearch.sdk.http.request.BasicRequest.create(BasicRequest.java:22)
	at com.meilisearch.sdk.HttpClient.post(HttpClient.java:95)
	at com.meilisearch.sdk.Client.multiSearch(Client.java:433)
```

**Environment (please complete the following information):**
- OS: macos
- Meilisearch version: 1.9.0
- meilisearch-java version: v.0.14.0

**Comment by sandeepsandy62** [comment]
Hi @curquiza  & @jdvalenzuelah 

I've identified two potential approaches to resolve this issue:

1. **Expose the `queries` field in `MultiSearchRequest` via public getter and setter methods**, allowing Jackson to serialize it using its default behavior.

2. **Implement a custom serializer for `MultiSearchRequest`**, in case we prefer not to expose the `queries` field directly.

Please advise on which approach is preferred so we can proceed with the fix and close this issue.

**Comment by curquiza** [comment]
thank you @sandeepsandy62 

Closing this!
